[project]
name = "bismillah-mbd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sleepy", email = "nemorzgm.05@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.141.1",
]

[project.scripts]
bismillah-mbd = "bismillah_mbd:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
